### ISSUE TITLE
App Connection Bluetooth failed

### ISSUE THREAD

**Issue by JoiLa** [Fabi019/hid-barcode-scanner#212]
OS Info: Win10

Problem: App Connection Win10 Bluetooth , Show Dialog Info  `Please wait`.  And after Exit App , I try again Connection Failed

Discuss: this problem from Bluetooth devices  ?

**Comment by Fabi019** [comment]
Hi, thanks for the report. Did you unpair the PC from the phone and also removed (unistalled) the phone device on the PC? 

From within the app you can do this by clicking on the three dots and then choose "Unpair".
On Windows you would need to go to your bluetooth devices and remove it from there.

After that make sure that the PC is visible. In the app refresh the device list to start a new scan and choose the PC from the list.

This is the most common cause of all connection related problems. Let me know if that helped.
