### ISSUE TITLE
before send to device, use the JavaScript language to  process the codedata string

### ISSUE THREAD

**Issue by egwang186** [Fabi019/hid-barcode-scanner#236]
please surport the way to process the raw data of the code to the customize data, then send to device

**Comment by Fabi019** [comment]
> please surport the way to process the raw data of the code to the customize data, then send to device

Hi, thank you very much for the good idea.
For basic transformations it is currently already possible to extract specific parts from a code using a capture group in the regex and use that in the "Custom template" to add for example more additional characters or to just send it as it is.
However with using JavaScript there would be alot more possibilities. I will look into how much additional overhead adding a JavaScript engine would create and how it can be integrated best.

**Comment by egwang186** [comment]
usually there are more than one type of code(code128,  codebar,  pdf417) when scanning, i need to use if..else.. to process the data one by one, it's very difficult for Regex
