### ISSUE TITLE
Custom scanner overlay area

### ISSUE THREAD

**Issue by Fabi019** [Fabi019/hid-barcode-scanner#257]
Instead of the predefined camera overlays for barcode/qr-code add a third option ("Custom") which allows the user to adjust the overlay size/position while in the scanner screen.

**Comment by Athep** [comment]
This is really needed. A very good app, but unusable for me as it is now. A red line to position over the barcode that should be read would be the best.

**Comment by Athep** [comment]
This is a very good app, and the fact that it works via BT instead of WiFi is very useful. So I really hope it is possible to make it possible to manually resize the scan window, or point with a red line over the code which would be the best.
