### ISSUE TITLE
Send to Device button stopped appearing

### ISSUE THREAD

**Issue by spzmd** [Fabi019/hid-barcode-scanner#312]
I was able to scan a barcode using this app the very first time I used this, but tried again an hour later and it captures the code but the send to device button won't appear. I'm using an Android device and trying to populate fields in an application on my PC. Again, worked great the first time but it hasn't worked since then. Any advice?

Keith

**Comment by Fabi019** [comment]
Thank you for using the app 😀
When there is no send button, this usually means that the phone is currently not connected (no "connected with: ..." in the top bar). This can happen when the connection gets interrupted. I already have a feature in #309 that will make this more clear when no device is currently connected. To reconnect either navigate back to the devices or try to enable auto-connect from the settings. Let me know if this helped.

**Comment by spzmd** [comment]
Hello

Thank you for your response. I will try this out again in a few days.
Appreciate your help and thanks for providing this great app!

**Comment by spzmd** [comment]
Thank you. Please close this case.
