### ISSUE TITLE
Regular Expression (RegEx) Filter not working

### ISSUE THREAD

**Issue by KithNim** [Fabi019/hid-barcode-scanner#325]
I have checked my filter RegEx syntax on regex101.com to confirm that it works on the QR code string of text that your app reads without the RegEx filter not in place. I only need the embedded serial number. However, as soon as I put any RegEx filter syntax into the Settings the app will no longer scan any QR code that it is detecting. I have detection dots turned on so I know that it sees the QR.

**Comment by Fabi019** [comment]
Hi, the regex needs to match the whole code to not be filtered out. What should work in your case would be something like ".*SERNO=([^,]+).*" (With the part to be extracted in the capture group)
Let me know if that helped you 😀

**Comment by KithNim** [comment]
Sorry of the delay in responding, Thanksgiving Holiday happened.
Anyway - I tested the ". * SERNO=([^,]+) . * " regex code on regex101.com website so I could read what each part of the code was doing. It is odd that the other expression did not work, however the ". * SERNO=([^,]+). * " code did work.
I was worried because it started to just give the detection dots again, but after the camera refocused it did return and beep !

It gave me just the **B8A41FCA82BC**

This is exactly what I needed to get through this big box of old product tags.
**Thanks!**


Below is how regex101.com describes the elements of that regex code line:


~~~~~~~~~~
Point    matches any character (except for line terminators)
Asterisk   matches the previous token between zero and unlimited times, as many times as possible, giving back as needed (greedy)
SERNO=  matches the characters SERNO= literally (case sensitive)
1st Capturing Group ([^,]+)    Match a single character not present in the list below [^,]
Plus   matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
Comma    matches the character , with index 4410 (2C16 or 548) literally (case sensitive)
Point    matches any character (except for line terminators)
Asterisk   matches the previous token between zero and unlimited times, as many times as possible, giving back as needed (greedy)
~~~~~~~~~~

I did not include the expression flags but they are defined as this:
Global pattern flags 
g modifier: global. All matches (don't return after first match)
m modifier: multi line. Causes ^ and $ to match the begin/end of each line (not only begin/end of string)

**Comment by Fabi019** [comment]
Glad it worked 👍

> Anyway - I tested the ". * SERNO=([^,]+) . * " regex code on regex101.com website so I could read what each part of the code was doing. It is odd that the other expression did not work, however the ". * SERNO=([^,]+). * " code did work.

Yes it is important, that the whole code is matched and not just the part to extract. That is why I added the ".\*" to the start and end of the regex. When looking at both regexes for example on regex101 you can see that the first one only matches the "B8A41FCA82BC" part while with the second regex the whole line is highlighted and matched. Lastly I just added the capture group "()" around the part to extract.

Feel free to open another issue if you have any further questions in the future ☺️
