### ISSUE TITLE
Custom template ok button not hilighting

### ISSUE THREAD

**Issue by saurabhvejani** [Fabi019/hid-barcode-scanner#334]
![Screenshot_20241230_145835_BT Scanner](https://github.com/user-attachments/assets/38205d20-e924-4533-88b5-a35c63551051)
###

**Comment by Fabi019** [comment]
For the custom template to be valid (and the OK button enabled), it needs to also contain the actual value of the code in the template. This means either the "{CODE}" placeholder for the plain value or "{CODE_B64}"/"{CODE_HEX}" for the value in base64 or hexadecimal is required to be in the template. 
Let me know if this helped 😀

**Comment by saurabhvejani** [comment]
it worked
Thank You
